### ISSUE TITLE
Travis CI not recognizing failed unit tests

### ISSUE THREAD

**Issue by gordonje** [opencivicdata/python-opencivicdata#108]
I think part of the reason we missed some of the mistakes that resulted in PR #106 was that the Travis CI builds were succeeding, showing green checkmarks, but when you drill into the individual jobs, we found the purest failures.

Any ideas why this might be happening? Nothing obvious was jumping out for me.

**Comment by fgregg** [comment]
I just pushed a fix for this. https://github.com/opencivicdata/python-opencivicdata/commit/131957dbe556ab20171b680f6466f9b06f90fd13
