### ISSUE TITLE
Bill of address/impeachment classification

### ISSUE THREAD

**Issue by estaub** [opencivicdata/python-opencivicdata#115]
The New Hampshire and Massachusetts constitutions allow for a "Bill of Address" by which a judge can be removed from office.  It's very similar to impeachment; both houses have to vote up the address.  

There's currently no bill classification corresponding to such a bill, or for any impeachment, in [the bill classification list](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/common.py#L77).  Should there be?

As far as I can tell, the term "Bill of Address" is peculiar to NH and MA.  I don't know how many other states have judicial impeachment, and under what name.  Many appear to have gubernatorial impeachment.

**Comment by jamesturk** [comment]
interesting, do we have a live example?

**Comment by estaub** [comment]
@jamesturk See e.g. http://www.gencourt.state.nh.us/bill_Status/bill_status.aspx?lsr=2286&sy=2018&sortoption=&txtsessionyear=2018 .  The "A" in HA1 (the bill title) was/is being mapped to OCD-invalid "address", in https://github.com/openstates/openstates/blob/master/openstates/nh/bills.py#L112.

The OpenStates PR referencing this (see above) patches the "A" to map to "bill", just to get things working again for now.
