### ISSUE TITLE
add `type` to EventDocument and EventMedia

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/python-opencivicdata#125]
There are types of documents and media very commonly associated with legislative events:

- agenda
- minutes
- transcript
- testimony
- audio recording
- video recording
- video testimony

For downstream work, it would be very helpful to be able to get a document or media by type instead of having it infer it from the name or contents of the document.

@jamesturk, what do you think. If acceptable, I'll make a PR.

**Comment by jamesturk** [comment]
sounds good to me
